# Numpy

In [1]:
import numpy as np

In [2]:
M = np.array([[1, 2], [3, 4]])
print(M)

[[1 2]
 [3 4]]


In [3]:
M[1,1]

4

In [4]:
M[:,1]

array([2, 4])

In [7]:
print(f"Matice M má rozměr {M.shape}, počet prvků {M.size} a dimenzi {M.ndim}")

Matice M má rozměr (2, 2), počet prvků 4 a dimenzi 2


In [13]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.ones([2,2], dtype=int)                                                                       #dtype=int

array([[1, 1],
       [1, 1]])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
x, y = np.mgrid[0:3, 0:3]
print(x)
print(y)

[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [21]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])