# Numpy (algebra)

In [22]:
import numpy as np
C = np.array([[1,2],[3,4]])
print(C)
print(C*C)
print(np.dot(C,C))

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [20]:
A = np.array([[n+m for n in range(5)] for m in range(5)])
A

array([[1, 2],
       [3, 4]])

In [8]:
B = np.array([[[n+m+k for n in range(5)] for m in range(5)] for k in range(5)])
B

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8]],

       [[ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9]],

       [[ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10]],

       [[ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11]],

       [[ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12]]])

In [10]:
v = np.array([0,1,0,1,0])
v

array([0, 1, 0, 1, 0])

In [11]:
B*B

array([[[  0,   1,   4,   9,  16],
        [  1,   4,   9,  16,  25],
        [  4,   9,  16,  25,  36],
        [  9,  16,  25,  36,  49],
        [ 16,  25,  36,  49,  64]],

       [[  1,   4,   9,  16,  25],
        [  4,   9,  16,  25,  36],
        [  9,  16,  25,  36,  49],
        [ 16,  25,  36,  49,  64],
        [ 25,  36,  49,  64,  81]],

       [[  4,   9,  16,  25,  36],
        [  9,  16,  25,  36,  49],
        [ 16,  25,  36,  49,  64],
        [ 25,  36,  49,  64,  81],
        [ 36,  49,  64,  81, 100]],

       [[  9,  16,  25,  36,  49],
        [ 16,  25,  36,  49,  64],
        [ 25,  36,  49,  64,  81],
        [ 36,  49,  64,  81, 100],
        [ 49,  64,  81, 100, 121]],

       [[ 16,  25,  36,  49,  64],
        [ 25,  36,  49,  64,  81],
        [ 36,  49,  64,  81, 100],
        [ 49,  64,  81, 100, 121],
        [ 64,  81, 100, 121, 144]]])

In [12]:
B*v

array([[[ 0,  1,  0,  3,  0],
        [ 0,  2,  0,  4,  0],
        [ 0,  3,  0,  5,  0],
        [ 0,  4,  0,  6,  0],
        [ 0,  5,  0,  7,  0]],

       [[ 0,  2,  0,  4,  0],
        [ 0,  3,  0,  5,  0],
        [ 0,  4,  0,  6,  0],
        [ 0,  5,  0,  7,  0],
        [ 0,  6,  0,  8,  0]],

       [[ 0,  3,  0,  5,  0],
        [ 0,  4,  0,  6,  0],
        [ 0,  5,  0,  7,  0],
        [ 0,  6,  0,  8,  0],
        [ 0,  7,  0,  9,  0]],

       [[ 0,  4,  0,  6,  0],
        [ 0,  5,  0,  7,  0],
        [ 0,  6,  0,  8,  0],
        [ 0,  7,  0,  9,  0],
        [ 0,  8,  0, 10,  0]],

       [[ 0,  5,  0,  7,  0],
        [ 0,  6,  0,  8,  0],
        [ 0,  7,  0,  9,  0],
        [ 0,  8,  0, 10,  0],
        [ 0,  9,  0, 11,  0]]])

In [13]:
np.dot(B,B)

array([[[[ 30,  40,  50,  60,  70],
         [ 40,  50,  60,  70,  80],
         [ 50,  60,  70,  80,  90],
         [ 60,  70,  80,  90, 100],
         [ 70,  80,  90, 100, 110]],

        [[ 40,  55,  70,  85, 100],
         [ 55,  70,  85, 100, 115],
         [ 70,  85, 100, 115, 130],
         [ 85, 100, 115, 130, 145],
         [100, 115, 130, 145, 160]],

        [[ 50,  70,  90, 110, 130],
         [ 70,  90, 110, 130, 150],
         [ 90, 110, 130, 150, 170],
         [110, 130, 150, 170, 190],
         [130, 150, 170, 190, 210]],

        [[ 60,  85, 110, 135, 160],
         [ 85, 110, 135, 160, 185],
         [110, 135, 160, 185, 210],
         [135, 160, 185, 210, 235],
         [160, 185, 210, 235, 260]],

        [[ 70, 100, 130, 160, 190],
         [100, 130, 160, 190, 220],
         [130, 160, 190, 220, 250],
         [160, 190, 220, 250, 280],
         [190, 220, 250, 280, 310]]],


       [[[ 40,  55,  70,  85, 100],
         [ 55,  70,  85, 100, 115],
         [ 70,  

In [ ]:
np.dot(B,v)